### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by Menganitou** [leandrotk/pokehooks-labs#12]
Hi there! I spotted a infinite loop while i was playing with the app in codesandbox. 

[https://codesandbox.io/s/billowing-wildflower-mm5dd?file=/src/Pokemon/PokemonsList.js](url)

Here is the source of the problem:
![image](https://user-images.githubusercontent.com/10880950/80274742-eb7d3580-86dc-11ea-87c5-051dfee01fd2.png)

Inside `PokemonContext.js` addPokemons must be wrapped with useCallback(...addPokemons, [dispatch]);
`  const addPokemons = useCallback(
    pokemons => dispatch({ type: ADD_POKEMONS, pokemons }),
     [dispatch]
  );`

Also. Inside `PokemonList.js` you can leave the dependency array of useEffect() empty, so it executes just one time. This way you dont need to use useCallback. :)

I think that the problems is that addPokemons function reference is always being updated when the state in PokemonProvider receive an update.

**Comment by leandrotk** [comment]
Fixed removing the `addPokemons` from the dependency array. Also I couldn't use the `useCallback` in the `PokemonContext` because it isn't a component or a custom hook.
